'use strict';

// Owner request (2026-09-22, mid-incident on the notification bug): a visible build/version
// indicator in the tray menu, specifically to answer "is this a stale process or the current
// build?" — the exact question the notification investigation lost a whole diagnostic round to
// answering by hand (process-start-time vs. source-mtime archaeology). A bare `app.getVersion()`
// (e.g. "0.1.0") does NOT answer that: every dev run and every packaged build shares the same
// package.json version between releases.
//
// Build identity now comes from `build-info.json` (generated by
// `scripts/generate-build-info.js`, owned by ci-cd-engineer — see that script's header comment
// for the full contract and resolution order). That file carries a GitVersion-derived version,
// short commit SHA, branch, and whether the build was produced by CI or locally — a strictly
// more reliable per-build marker than this module used to derive from `fs.statSync` on its own
// entry file: an mtime collapses or loses meaning once files are packed into an asar archive, and
// says nothing about which commit is actually running. There is deliberately no mtime-based
// fallback here anymore — a fallback that quietly produces a different, less reliable answer is
// how you get a label nobody can trust.

/**
 * readBuildInfo(appGetAppPath)
 *
 * Reads and parses `build-info.json` from the app's root directory (same directory as
 * `package.json`, in both dev and packaged layouts — see `build-info.json`'s own contract
 * comment). Never throws: a missing file (fresh clone, or a dev run where `prepack`/`predist`
 * never fired) or malformed JSON both resolve to `null` rather than crashing the tray menu build.
 *
 * @param {() => string} appGetAppPath Typically Electron's `app.getAppPath`, injected so this
 *   stays testable without a real Electron runtime.
 * @returns {object|null} The parsed build-info object, or `null` if it is missing/unreadable/
 *   malformed.
 */
function readBuildInfo(appGetAppPath) {
  try {
    const fs = require('fs');
    const path = require('path');
    const filePath = path.join(appGetAppPath(), 'build-info.json');
    const raw = fs.readFileSync(filePath, 'utf8');
    const parsed = JSON.parse(raw);
    if (!parsed || typeof parsed !== 'object') return null;
    return parsed;
  } catch (err) {
    return null;
  }
}

/**
 * buildVersionLabel(buildInfo)
 *
 * Builds the exact string shown as the tray menu's disabled version line, from an already-parsed
 * `build-info.json` object (or `null`/malformed input — this stays a pure function so it is
 * testable with no filesystem access; the caller does the reading via `readBuildInfo`).
 *
 * Format: `"<version> (<sha>, <ci|local>)"`, e.g.
 * `"0.0.1-14 (00b6e49, local)"` — version answers "which release line", the short sha answers
 * "which exact commit" (the version alone repeats across commits on the same branch pre-tag),
 * and ci/local answers "was this built by the release pipeline or on someone's machine".
 *
 * @param {object|null} buildInfo Parsed `build-info.json` contents (see
 *   `scripts/generate-build-info.js` for the field contract: version, shortSha, branch,
 *   buildSource, builtAt), or `null`/malformed.
 * @returns {string} The tray label, or `"build info unavailable"` when `buildInfo` is `null` or
 *   missing the fields this label needs — an honest unknown-build marker rather than a fabricated
 *   version or a silent fallback to `package.json`'s static version.
 */
function buildVersionLabel(buildInfo) {
  if (!buildInfo || typeof buildInfo !== 'object') return 'build info unavailable';

  const { version, shortSha, buildSource } = buildInfo;
  if (typeof version !== 'string' || !version) return 'build info unavailable';

  const sha = typeof shortSha === 'string' && shortSha ? shortSha : 'unknown sha';
  const source = buildSource === 'ci' || buildSource === 'local' ? buildSource : 'unknown source';

  return `${version} (${sha}, ${source})`;
}

module.exports = { readBuildInfo, buildVersionLabel };
